<?php

use App\Http\Controllers\CommunityController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SessionsController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application.
| These routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index'])->name('welcome');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Routes for services
Route::get('/services/available', [ServiceController::class, 'availableServices'])->name('services.available');

// Routes for communities
Route::get('/community/available', [CommunityController::class, 'availableCommunity'])->name('community.available');

// Route for about page
Route::get('/about', [WelcomeController::class, 'Acerca'])->name('about');

// Route for contact page
Route::get('/contact', [WelcomeController::class, 'Contacto'])->name('contact');

// Route for testimonials
Route::get('/testimonials', [WelcomeController::class, 'Testimonios'])->name('testimonios');

// Route for user view
Route::get('/usuarios', function () {
    return view('usuarios');
})->name('usuarios')->middleware('auth');

// Route for admin view
Route::get('/admin/dashboard', function () {
    return view('admin.dashboard');
})->name('admin.dashboard')->middleware('auth.admin');

// Routes for offers
Route::get('/offers', [ServiceController::class, 'Offer'])->name('offer');

// CRUD routes generated by ibex/crud-generator
Route::resource('services', ServiceController::class);

// CRUD routes generated by ibex/crud-generator
Route::resource('communities', CommunityController::class);

// Route for service detail
Route::get('/service/{id}', [ServiceController::class, 'showdetail'])->name('service.detail');

// Authentication routes
Route::get('/register', [RegisterController::class, 'create'])->name('register.index');
Route::post('/register', [RegisterController::class, 'store'])->name('register.store');
Route::get('/login', [SessionsController::class, 'create'])->name('login.index');
Route::post('/login', [SessionsController::class, 'store']);
Route::get('/logout', [SessionsController::class, 'destroy'])->name('logout');
Route::get('/admin', [AdminController::class, 'index'])->middleware('auth.admin')->name('admin.index');
